<?php

namespace App\Constants;

return [

    'OUR_SOLUTION_MAX_IMAGE_SIZE'=>'300',
    'OUR_SOLUTION_MAX_IMAGE_MIN_SIZE'=>'5',
    //Home
    'SLIDER_IMAGE_MAX_SIZE'=>'2048',
    'SLIDER_IMAGE_MIN_SIZE'=>'180',

    'COURSES_OFFERED_IMAGE_MAX_SIZE'=>'300',
    'COURSES_OFFERED_IMAGE_MIN_SIZE'=>'5',

    'TESTIMONIAL_IMAGE_MAX_SIZE'=>'500',
    'TESTIMONIAL_IMAGE_MIN_SIZE'=>'10',

    'GALLERY_IMAGE_MAX_SIZE'=>'1024',
    'GALLERY_IMAGE_MIN_SIZE'=>'50',

    'OUR_RESULT_IMAGE_MAX_SIZE'=>'1024',
    'OUR_RESULT_IMAGE_MIN_SIZE'=>'10',
];